# Site settings
title: CureFFI.org
twitter_username: cureffi
github_username: ericminikel
description: "Eric Vallabh Minikel's blog"
baseurl: ""
url: "http://www.cureffi.org"

# Build settings
markdown: kramdown
permalink: pretty
