# Site settings
title: CureFFI.org
twitter_username: cureffi
github_username: ericminikel
description: "Eric Vallabh Minikel's blog"
baseurl: "http://www.cureffi.com"
url: "http://www.cureffi.com"

# Build settings
markdown: kramdown
permalink: pretty
