# Site settings
title: CureFFI.org
twitter_username: cureffi
github_username: ericminikel
description: "Not if, when."
baseurl: ""
url: "http://www.cureffi.org"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "tables"]
permalink: pretty
