# Site settings
title: CureFFI.org
twitter_username: cureffi
github_username: ericminikel
description: "Eric Vallabh Minikel's blog"
baseurl: "http://ericminikel.github.io/cureffi/"
url: "http://ericminikel.github.io/cureffi/"

# Build settings
markdown: kramdown
permalink: pretty
